name: Tests Coverage

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

env:
  TARPAULIN_VERSION: 0.20.1

jobs:
  test:
    name: Coverage Report
    runs-on: custom-runner
    steps:
      - name: Cancel Previous Runs
        # Only cancel non-master branch runs
        if: ${{ github.ref != 'refs/heads/master' }}
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Clean
        run: |
          df -h
          curl -s https://raw.githubusercontent.com/apache/flink/master/tools/azure-pipelines/free_disk_space.sh | bash

      

      - name: Installing Prerequisites
        run: sudo apt-get update
      - name: Installing Prerequisites 1
        run: curl https://sh.rustup.rs -sSf -y | sh 
      - name: Installing Prerequisites 2
        run: sudo apt-get install -y git clang curl llvm libudev-dev libssl-dev
      - name: Installing Prerequisites 3
        run: git config --global submodule.recurse true
        
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-02-19
          components: rustfmt
          target: wasm32-unknown-unknown
          default: true
      
      #- uses: actions/checkout@v2
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3
      
      #- name: openssl
      #  run: 
      #    export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib64
      #    sudo ldconfig

      - name: Generate code coverage
        run: |
          wget https://github.com/xd009642/tarpaulin/releases/download/${{ env.TARPAULIN_VERSION }}/cargo-tarpaulin-${{ env.TARPAULIN_VERSION }}-travis.tar.gz
          tar -zxvf cargo-tarpaulin-${{ env.TARPAULIN_VERSION }}-travis.tar.gz -C $HOME/.cargo/bin
          make Cargo.toml
          cargo tarpaulin --verbose --no-fail-fast --workspace --timeout 300 --out Xml
          environment:
            RUSTFLAGS: --cfg procmacro2_semver_exempt
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
